#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wanderer"
name = "Wanderer"
description.en = "Self-hosted trail database. Save your adventures! "
description.fr = "Base de données de trails auto-hébergée. Sauvegardez vos aventures !"

version = "0.9.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://wanderer.to/"
demo = "https://demo.wanderer.to/"
admindoc = "https://wanderer.to/getting-started/installation/"
userdoc = "https://wanderer.to/"
code = "https://github.com/Flomp/wanderer"
fund = "https://buymeacoffee.com/wanderertrails"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.disable_signup]
    ask.en = "Enable sign up?"
    ask.fr = "Autoriser les inscriptions ?"
    type = "boolean"
    yes = true
    no = false

[resources]
 
     [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Flomp/wanderer/archive/refs/tags/v0.9.0.tar.gz"
    sha256 = "13595f5e8be36dea9bc64ca2b0546075fb4f08a634f96eba627a8eaa7694ebe3"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.meili]
    amd64.url = "https://github.com/meilisearch/meilisearch/releases/download/v1.10.2/meilisearch-linux-amd64"
    amd64.sha256 = "55bd847a256899214a08373491fc1484a977b6ac79033151551388f27bebc3fb"
    arm64.url = "https://github.com/meilisearch/meilisearch/releases/download/v1.10.2/meilisearch-linux-aarch64"
    arm64.sha256 = "0d67fc81232bcfad2ee748af8fcc888584b3f42ffbde816b5aa8e850abeaf545"
    rename = "meilisearch"
    in_subdir = false
    extract = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^meilisearch-linux-amd64$"
    autoupdate.asset.arm64 = "^meilisearch-linux-aarch64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    meili.default = 7700
    pocketbase.default = 8090
