#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wanderer"
name = "Wanderer"
description.en = "Self-hosted trail database. Save your adventures! "
description.fr = "Base de données de trails auto-hébergée. Sauvegardez vos aventures !"

version = "0.10.0~ynh2"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://wanderer.to/"
demo = "https://demo.wanderer.to/"
admindoc = "https://wanderer.to/getting-started/installation/"
userdoc = "https://wanderer.to/"
code = "https://github.com/Flomp/wanderer"
fund = "https://buymeacoffee.com/wanderertrails"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.disable_signup]
    ask.en = "Enable sign up?"
    ask.fr = "Autoriser les inscriptions ?"
    type = "boolean"

[resources]
 
     [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Flomp/wanderer/archive/refs/tags/v0.10.0.tar.gz"
    sha256 = "c15b3d75339ca0b6891f8a3ce0f83efa41cf6b29b6b33e2c5574d1b065eac65f"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.meili]
    amd64.url = "https://github.com/meilisearch/meilisearch/releases/download/v1.11.1/meilisearch-linux-amd64"
    amd64.sha256 = "86d46abc97b700515964861421a5aa2413fbec2015924af4d6941bacb982b3b9"
    arm64.url = "https://github.com/meilisearch/meilisearch/releases/download/v1.11.1/meilisearch-linux-aarch64"
    arm64.sha256 = "76374d87078af3f8a5c3b25d22dced8cfa756c4c8b82c677518bd2973cdb333b"
    rename = "meilisearch"
    in_subdir = false
    extract = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/meilisearch/meilisearch"
    autoupdate.asset.amd64 = "^meilisearch-linux-amd64$"
    autoupdate.asset.arm64 = "^meilisearch-linux-aarch64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    meili.default = 7700
    pocketbase.default = 8090
    pocketbase.fixed = true
